export const LOAD_RESOURCES          = 'LOAD_RESOURCES';
export const FILTER_LESSON_RESOURCES = 'FILTER_LESSON_RESOURCES';
export const FILTER_TYPE_RESOURCES   = 'FILTER_TYPE_RESOURCES';
export const SEARCH_RESOURCES        = 'SEARCH_RESOURCES';
